
# 2.05 / SQL 시험

#Q1
CREATE TABLE MY_MEMBER(
	MEM_NUM INT PRIMARY KEY
	, MEM_ID VARCHAR(10) NOT NULL UNIQUE
	, MEM_PW VARCHAR(10) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_AGE INT
	, MEM_EMAIL VARCHAR(30) UNIQUE
);

#Q2
INSERT INTO MY_MEMBER (MEM_NUM , MEM_ID , MEM_PW , MEM_NAME , MEM_AGE , MEM_EMAIL)
VALUES (101, 'kim' , '1234' , '김자바' , 30 , 'kim@gmail.com');

INSERT INTO MY_MEMBER (MEM_NUM , MEM_ID , MEM_PW , MEM_NAME , MEM_AGE , MEM_EMAIL)
VALUES (102, 'hong' , '5678' , '홍자바' , 30 , 'hong@gmail.com');

SELECT * FROM MY_MEMBER;

#Q3
UPDATE MY_MEMBER
SET
MEM_NAME = '유관순'
, MEM_AGE = (MEM_AGE +5)
WHERE MEM_NUM = '101';

SELECT * FROM MY_MEMBER;

#Q4
SELECT EMPNO , ENAME , SAL , COMM AS '인센티브'
FROM emp
WHERE SAL BETWEEN (500 AND 3000)
AND COMM IS NOT NULL;

#Q5
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp
WHERE ENAME LIKE '%기' OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

#Q6
SELECT EMPNO, ENAME, DEPTNO,
	CASE
		WHEN DEPTNO = 10 THEN '인사부'
		WHEN DEPTNO = 20 THEN '영업부'
		WHEN DEPTNO = 30 THEN '개발부'
		ELSE '생산부'
		END AS DNAME
FROM emp;

#Q7
SELECT * FROM emp;
SELECT EMPNO , ENAME, HIREDATE ,IFNULL(COMM, 0) AS COMM
FROM emp
WHERE TO_CHAR(HIREDATE , 'MM') = 01
ORDER BY HIREDATE ;

#Q8

#Q9

#Q10
SELECT EMPNO, ENAME, HIREDATE, SAL, E.DEPTNO, DNAME
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO
WHERE DNAME != '인사부'
AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;

