
#Q1
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY
	, BOOK_NAME VARCHAR(10) NOT NULL
	, WRITER VARCHAR(10) NOT NULL
	, BOOK_PRICE INT
	, MAKER VARCHAR(10) DEFAULT '미지정'
	, BOOK_DATE DATE DEFAULT SYSDATE()
);

#Q2
INSERT INTO BOOK_INFO
VALUES(
	101
	, '자바기초'
	, '홍길동'
	, 30000
	, 'A출판'
	, '2025-02-15'
);

INSERT INTO BOOK_INFO
VALUES(
	102
	, '리액트기초'
	, '이순신'
	, 20000
	, 'B출판'
	, '2025-01-22'
);

#Q3
UPDATE book_info
SET
	BOOK_NAME = '자바_고급'
	, BOOK_PRICE = 25000
	, MAKER = 'IT출판'
WHERE BOOK_NUM = 101;

#Q4
SELECT EMPNO , ENAME , SAL , COMM AS '인센티브'
FROM emp
WHERE SAL BETWEEN (500 AND 3000)
AND COMM IS NOT NULL;

#Q5
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp
WHERE ENAME LIKE '%병%' OR ENAME LIKE '%김%'
ORDER BY JOB ASC, EMPNO DESC;

#Q6
SELECT EMPNO, ENAME, DEPTNO,
	CASE
		WHEN DEPTNO = 10 THEN '인사부'
		WHEN DEPTNO = 20 THEN '영업부'
		WHEN DEPTNO = 30 THEN '개발부'
		ELSE '생산부'
		END AS DNAME
FROM emp;

#Q7
SELECT EMPNO , ENAME, HIREDATE ,IFNULL(COMM, 0) AS COMM
FROM emp
WHERE TO_CHAR(HIREDATE , 'MM') % 2 = 0
ORDER BY HIREDATE ASC;

#Q8
SELECT EMPNO, ENAME, HIREDATE, SAL, E.DEPTNO, DNAME
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO
WHERE DNAME != '인사부'
AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;

#Q9
SELECT EMPNO, E.DEPTNO, DNAME, SUBSTR(ENAME, 2) AS '이름'
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO
WHERE TO_CHAR(HIREDATE , 'YYYY') BETWEEN 2003 AND 2007;

#Q10
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, D.ENAME, D.JOB
FROM emp E
JOIN EMP D
ON E.MGR = D.EMPNO;

