
CREATE TABLE BOARD_REPLY(
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CONTENT VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE()
	, BOARD_NUM INT NOT NULL REFERENCES board (BOARD_NUM)
);

#외래키 작성 : BOARD테이블을 참조하여 BOARD_NUM을 작성
#외래키는 NULL을 입력할 수 있기 때문에 NOT NULL을 꼭 추가한다.
#BOARD_NUM INT NOT NULL REFERENCES board (BOARD_NUM)

DROP TABLE BOARD_REPLY;

SELECT * FROM board;

INSERT INTO BOARD_REPLY VALUES(
1, '첫 댓글 입니다.', '홍자바', NOW(), 1);

COMMIT;

SELECT * FROM board_reply;
