
# outer join
SELECT * FROM customer;
SELECT * FROM orders;

# 주문자 ID, 주문상품명, 주문수량, 주문자명을 INNER JOIN으로 조회
#INNER JOIN
SELECT O.CUSTOMER_ID, PRODUCT_NAME, ORDER_CNT, NAME
FROM ORDERS O
INNER JOIN CUSTOMER C
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

#서브쿼리
SELECT CUSTOMER_ID
	, PRODUCT_NAME
	, ORDER_CNT
	, (SELECT NAME 
		FROM customer 
		WHERE CUSTOMER_ID = orders.CUSTOMER_ID) AS NAME
FROM orders;

# OUTER JOIN
SELECT C.CUSTOMER_ID, 
	NAME, 
	PRODUCT_NAME, 
	ORDER_CNT
FROM orders O
RIGHT OUTER JOIN customer C
ON C.CUSTOMER_ID = O.CUSTOMER_ID;




SELECT * FROM book_category;
SELECT * FROM book;

# BOOK_CATEGORY 테이블에 존재하는 모든 카테고리에 대한
# 카테고리 번호, 카테고리이름, 책 이름, 책 가격을 조회
SELECT C.CATE_CODE, CATE_NAME, BOOK_NAME, BOOK_PRICE
FROM book_category C
INNER JOIN book B
ON C.CATE_CODE = B.CATE_CODE
ORDER BY BOOK_PRICE;


SELECT C.CATE_CODE, CATE_NAME, BOOK_NAME, BOOK_PRICE
FROM book_category C
LEFT OUTER JOIN book B
ON C.CATE_CODE = B.CATE_CODE;
