
CREATE TABLE ITEM_INFO(
	ITEM_NUM INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, SELLER VARCHAR(10)
	, ITEM_INTRO VARCHAR(20)
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO item_info(
	ITEM_NAME
	, ITEM_PRICE
	, SELLER
	, ITEM_INTRO
) VALUES(
	'상품1'
	, 45000
	, '이자바'
	, '상품1 입니다.'
);

COMMIT;

SELECT * FROM ITEM_INFO;

CREATE TABLE ORDER_INFO(
	ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NUM INT NOT NULL REFERENCES item_info(ITEM_NUM)        
	, BUYER VARCHAR(20) NOT NULL
	, BUY_CNT INT NOT NULL
	, BUY_PRICE INT NOT NULL
	, BUY_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM order_info;

SELECT I.ITEM_NAME
	, I.ITEM_PRICE
	, O.BUY_CNT
	, O.BUY_PRICE
	, O.BUYER
	, O.BUY_DATE
FROM order_info O
INNER JOIN item_info I
ON O.ITEM_NUM = I.ITEM_NUM;



#----------------------test연습------------------------
SELECT * FROM emp;
DESC emp;
SELECT * FROM dept;
DESC dept;

#모든 사원의 사번, 사원명, 급여, 부서번호, 부서명 조회
SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM emp E
INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO;

SELECT * FROM board;
DESC board;
SELECT * FROM board_reply;
DESC board_reply;

# BOARD_REPLY 테이블의 컬럼 변경
ALTER TABLE board_reply CHANGE COLUMN CONTENT REPLY_CONTENT VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN WRITER REPLY_WRITER VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN REG_DATE REPLY_REG_DATE DATETIME DEFAULT SYSDATE();

# 모든 게시글의 게시글 번호, 제목,
# 작성자 및 게시글에 달린 댓글 내용, 댓글 작성자 조회
SELECT B.BOARD_NUM , TITLE, WRITER
	, REPLY_CONTENT, REPLY_WRITER
FROM board B
INNER JOIN board_reply R
ON B.BOARD_NUM = R.BOARD_NUM;
