
CREATE TABLE SECURITY_MEMBER(
	MEM_EMAIL VARCHAR(100) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL #암호화 되면 글자가 길어져서 VARCHAR(100)은 줘야함
	, MEM_NAME VARCHAR(100) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL
);

SELECT * FROM SECURITY_MEMBER;
DELETE FROM SECURITY_MEMBER WHERE MEM_EMAIL = "admin";

COMMIT;