
SELECT * FROM study_student;

-- Q1
SELECT STU_NUM 학생번호, STU_NAME 학생명, KOR_SCORE 국어점수, ENG_SCORE 영어점수
FROM STUDY_STUDENT
WHERE KOR_SCORE >= 60 AND ENG_SCORE >= 70;

-- Q2
SELECT * FROM study_student
WHERE (CLASS_NAME = '디자인반' OR CLASS_NAME = '영상반')
AND HOBBY IS NOT NULL;

-- Q3
SELECT STU_NUM, STU_NAME, KOR_SCORE
FROM study_student
WHERE STU_NAME LIKE '김%'
AND KOR_SCORE BETWEEN 70 AND 85
ORDER BY STU_NUM DESC;

-- Q4
SELECT STU_NUM, STU_NAME, CLASS_NAME, ENG_SCORE
FROM study_student
WHERE HOBBY IS NOT NULL
ORDER BY CLASS_NAME ASC, ENG_SCORE DESC;

-- Q5
SELECT * FROM study_student
WHERE KOR_SCORE + ENG_SCORE >= 170;

-- Q6
SELECT STU_NUM , STU_NAME,
KOR_SCORE, ENG_SCORE, KOR_SCORE + ENG_SCORE AS 총점
FROM study_student
WHERE CLASS_NAME != '영상반';
-- WHERE CLASS_NAME NOT IN ('영상반') // 위 WHERE절과 같다

-- Q7
SELECT DISTINCT HOBBY 취미종류 FROM study_student
WHERE HOBBY IS NOT NULL;
