
#상품정보 테이블
CREATE TABLE SHOP_ITEM(
	ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NAME VARCHAR(10)
	, ITEM_PRICE INT
	, ITEM_INTRO VARCHAR(20)
	, REG_DATE DATETIME DEFAULT SYSDATE()
);



SELECT * FROM SHOP_ITEM;
